In [1]:
import numpy as np

In [2]:
A_11 = np.array([[1.], [2.]])

In [3]:
A_12 = np.array([[3., 2],[1., 1]])

In [4]:
A_21 = np.array([-1.])

In [5]:
A_22 = np.array([0., 1])

In [6]:
A = np.block([[A_11, A_12], [A_21, A_22]])
A

array([[ 1.,  3.,  2.],
       [ 2.,  1.,  1.],
       [-1.,  0.,  1.]])

In [7]:
B_11 = np.array([1.])
B_12 = np.array([0., 1])
B_21 = np.array([[2.], [-1.]])
B_22 = np.array([[1., 1], [2., 0]])
B = np.block([[B_11, B_12], [B_21, B_22]])
B

array([[ 1.,  0.,  1.],
       [ 2.,  1.,  1.],
       [-1.,  2.,  0.]])

In [8]:
A@B

array([[ 5.,  7.,  4.],
       [ 3.,  3.,  3.],
       [-2.,  2., -1.]])

In [9]:
A_11 = A[0:2, 0]
A_12 = A[0:2, 1:3]
A_21 = A[2, 0]
A_22 = A[2:, 1:3]

In [10]:
B_11 = B[0, 0]
B_12 = B[0, 1:]
B_21 = B[1:, 0]
B_22 = B[1:, 1:]

In [11]:
A_11

array([1., 2.])

In [12]:
C_11 = A_11*B_11 + A_12@B_21
C_11

array([5., 3.])

In [13]:
C_12 = np.outer(A_11, B_12) + A_12 @ B_22
C_12

array([[7., 4.],
       [3., 3.]])

In [14]:
C_21 = A_21 * B_11 + A_22 @ B_21
C_21

array([-2.])

In [15]:
C_22 = A_21 * B_12 + A_22 @ B_22
C_22

array([[ 2., -1.]])

In [276]:
def sol_trinffil(A, b):
    '''Sustitucion hacia adelante por filas para matrices triangulares inferiores'
    Parameters
    ----------
    A: numpy array n-D
    b: numpy array 1-D

    Return
    ------
    out: numpy array 1-D, x talque Ax = b
    '''
    n = len(b)
    x = np.zeros(n)
    j = np.where(b!=0)[0][0]
    x[0] = b[0]/A[0,0]
    
    if n > 1:
        for i in range(j,n):
            x[i] = (b[i] - A[i, j:i] @ x[j:i])/A[i, i]

    return x

In [277]:
def sol_trinfcol(A, b):
    '''Sustitucion hacia adelante por columnas para matrices triangulares inferiores'
    Parameters
    ----------
    A: numpy array n-D (Matriz n x n)
    b: numpy array 1-D

    Return
    ------
    out: numpy array 1-D, x talque Ax = b
    '''
    n = len(b)
    x = np.copy(b) # esta linea es importante para no modificar b!
    j = np.where(b!=0)[0][0]
    
    if n > 1:
        for i in range(j, n-1):
            x[i] = x[i]/A[i, i]
            x[i+1:] = x[i+1:] - A[i+1:, i] * x[i]
           
    x[n-1] = x[n-1]/A[n-1,n-1]
       
    return x

In [278]:
def sol_trsupfil(A, b):
    '''Sustitucion hacia atras por filas para matrices triangulares superiores'
    Parameters
    ----------
    A: numpy array n-D con elementos de la diagonal principal no nula
    b: numpy array 1-D

    Return
    ------
    out: numpy array 1-D , x talque Ax = b
    '''
    n = len(b)
    x = np.zeros(n)
    j = np.where(b!=0)[0][-1]
    x[n-1] = b[n-1]/A[n-1, n-1]
    
    if n > 1:
        for i in range(j, -1 , -1):
            x[i] = (b[i] - A[i, i+1:] @ x[i+1:])/A[i, i]
            
    return x

In [279]:
def sol_trsupcol(A, b):
    '''Sustitucion hacia atras por columnas para matrices triangulares superiores'
    Parameters
    ----------
    A: numpy array n-D con elementos de la diagonal principal no nula
    b: numpy array 1-D

    Return
    ------
    out: numpy array 1-D , x talque Ax = b
    '''
    n = len(b)
    x = np.copy(b)
    j = np.where(b!=0)[0][-1]
    
    if n > 1:
        for i in range(j, 0 , -1):
            x[i] = x[i]/A[i, i]
            x[:i] = x[:i] - A[:i, i] * x[i] 
            
    x[0] = x[0]/A[0, 0]
    return x

In [294]:
A1 = np.array([[1., 0, 0, 0], 
          [-1., 1, 0, 0],
          [0., -1, 1, 0],
          [0., 0, -2, 2]])

b1 = np.array([0., 0, 1, 1])

In [295]:
x1 = sol_trinffil(A1, b1)
print('A1', A1, 'x1', x1, 'b1:', A1@x1 )

A1 [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -2.  2.]] x1 [0.  0.  1.  1.5] b1: [0. 0. 1. 1.]


In [296]:
x1 = sol_trinfcol(A1, b1)
print('A1', A1, 'x1', x1, 'b1:', A1@x1)

A1 [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0. -2.  2.]] x1 [0.  0.  1.  1.5] b1: [0. 0. 1. 1.]


In [297]:
A2 = np.array([[2., 0, 0, 0], 
          [-1., 2, 0, 0],
          [3., 1, -1, 0],
          [4., 1, -3, 3]])

b2 = np.array([2., 3, 2, 9])

In [298]:
x2 = sol_trinffil(A2, b2)
print('A2', A2, 'x2', x2, 'b2:', A2@x2 )

A2 [[ 2.  0.  0.  0.]
 [-1.  2.  0.  0.]
 [ 3.  1. -1.  0.]
 [ 4.  1. -3.  3.]] x2 [1. 2. 3. 4.] b2: [2. 3. 2. 9.]


In [299]:
x2 = sol_trinfcol(A2, b2)
print('A2', A2, 'x2', x2, 'b2:', A2@x2 )

A2 [[ 2.  0.  0.  0.]
 [-1.  2.  0.  0.]
 [ 3.  1. -1.  0.]
 [ 4.  1. -3.  3.]] x2 [1. 2. 3. 4.] b2: [2. 3. 2. 9.]


In [300]:
A3 = np.array([[9., 2, 4], 
          [0., -6, 3],
          [0., 0, 5]])

b3 = np.array([18., -2, 7])

In [301]:
x3 = sol_trsupfil(A3, b3)
print('A3', A3, 'x3', x3, 'b3:', A3@x3 )

A3 [[ 9.  2.  4.]
 [ 0. -6.  3.]
 [ 0.  0.  5.]] x3 [1.14814815 1.03333333 1.4       ] b3: [18. -2.  7.]


In [302]:
x3 = sol_trsupcol(A3, b3)
print('A3', A3, 'x3', x3, 'b3:', A3@x3 )

A3 [[ 9.  2.  4.]
 [ 0. -6.  3.]
 [ 0.  0.  5.]] x3 [1.14814815 1.03333333 1.4       ] b3: [18. -2.  7.]


In [303]:
A4 = np.array([[1., 2, -1, 1], 
          [0., 1, 0, -1],
          [0., 0, -1, 4],
          [0., 0, 0, 1]])

b4 = np.array([2., -1, 0, 0])

In [306]:
x4 = sol_trsupfil(A4, b4)
print('A4', A4, 'x4', x4, 'b4:', A4@x4)

A4 [[ 1.  2. -1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0. -1.  4.]
 [ 0.  0.  0.  1.]] x4 [ 4. -1.  0.  0.] b4: [ 2. -1.  0.  0.]


In [307]:
x4 = sol_trsupcol(A4, b4)
print('A4', A4, 'x4', x4, 'b4:', A4@x4 )

A4 [[ 1.  2. -1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0. -1.  4.]
 [ 0.  0.  0.  1.]] x4 [ 4. -1.  0.  0.] b4: [ 2. -1.  0.  0.]
